### ISSUE TITLE
Race condition in _find_gil impacts statistics collected?

### ISSUE THREAD

**Issue by cadedaniel** [chrisjbillington/gil_load#6]
Hi @chrisjbillington, thanks for your work!

I had a question regarding a race condition in _find_gil which I believe impacts statistics reported:
```cython
    for start, size in _get_data_segments():
        data_segment = <char *> start
        data_segment_nogil = <char *> malloc(size)
        with nogil:
            memcpy(data_segment_nogil, data_segment, size)

        if PY3:
            rc = _find_gil_py3(data_segment, data_segment_nogil, size)
        else:
            rc = _find_gil_py2(data_segment, data_segment_nogil, size)

        free(data_segment_nogil)

        if rc == 0:
            return
```

In Py3, this will basically copy the GIL data segment when `nogil` is used, then compare it to when the gil is obtained.

What prevents the Python interpreter from letting another thread take the gil before the memcpy takes place? Isn't there potential for gil_load to assume a memory segment represents the value of the GIL, but actually the memory segment represents some other value?

**Comment by chrisjbillington** [comment]
> What prevents the Python interpreter from letting another thread take the gil before the memcpy takes place?

[This bit](https://github.com/chrisjbillington/gil_load/blob/6760c588c5ada0e11c33dbff5ecc41a8c5f60642/gil_load/gil_load.pyx#L481) does:

```python
    if threading.active_count() > 1:
        raise RuntimeError("gil_load.init() must be called prior to other "
                           "threads being started")
```

Initialising `gil_load` after other threads have started is not supported, in order to avoid such a race condition.

**Comment by cadedaniel** [comment]
Ah, I see now. Thanks!

One last question: In Python3, how do you know that the first `int*` you encounter that changes from `0` to `1` is the GIL value? I wrote a small test and the statistics make sense when I add and remove a CPU-bound thread; is the GIL value guaranteed to be one of the first in the data segment?

**Comment by chrisjbillington** [comment]
No worries!

The GIL should be the only thing that changes in any data segments other than the one for `gil_load` itself (which is ignored). So it not only is the first thing to change, it should be the only one.

The only difference between the data segment being compared with itself is the `with nogil:` block, and the implementation of the GIL in Python 3 is such that it all comes down to the single int `gil_locked` - no other state in the Python interpreter is affected.

See [here](https://github.com/python/cpython/blob/ffa55d21b4a86ad8b4a43a9f597151e526541130/Python/ceval_gil.h#L14) for a description in the CPython source code:
```
    - The GIL is just a boolean variable (locked) whose access is protected
     by a mutex (gil_mutex), and whose changes are signalled by a condition
     variable (gil_cond). gil_mutex is taken for short periods of time,
     and therefore mostly uncontended.
```
I actually see that the variable is no longer a global `gil_locked` and is now `locked`, an attribute of a per-interpreter GIL struct if the `EXPERIMENTAL_ISOLATED_SUBINTERPRETERS` compile-time variable is set. I don't know if this is set by default in any Python releases, I would guess not since it's still named 'experimental'. But perhaps if subinterpreters become a standard feature, `gil_load` will need to reexamine its assumptions.

For now it still seems there is a single int in the data segment that represents whether the GIL is held.

**Comment by cadedaniel** [comment]
Thanks for the prompt and detailed responses. Cheers.
